In [1]:
import pandas as pd
data=pd.read_csv(r"swiggy.csv")
display(data.head())

,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [2]:
# Check the size of the data
display(data.shape)

(148541, 11)

In [3]:
# Remove duplicate rows
data = data.drop_duplicates()

# Re-check after dropping duplicate rows
display(data.shape)

(148541, 11)

In [4]:
# Check null/missing values
data.isnull().sum()

id                0
name             86
city              0
rating           86
rating_count     86
cost            131
cuisine          99
lic_no          229
link              0
address          86
menu              0
dtype: int64

In [5]:
# Drop the rows that has null values to improve the analysis
data = data.dropna(subset=['name', 'rating', 'rating_count', 'address','cost','cuisine','lic_no'])

# Check the shape for understanding
display(data.shape)

# Re-check the null values
display(data.isnull().sum())

(148255, 11)

id              0
name            0
city            0
rating          0
rating_count    0
cost            0
cuisine         0
lic_no          0
link            0
address         0
menu            0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148255 entries, 0 to 148540
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            148255 non-null  int64
 1   name          148255 non-null  object
 2   city          148255 non-null  object
 3   rating        148255 non-null  object
 4   rating_count  148255 non-null  object
 5   cost          148255 non-null  object
 6   cuisine       148255 non-null  object
 7   lic_no        148255 non-null  object
 8   link          148255 non-null  object
 9   address       148255 non-null  object
 10  menu          148255 non-null  object
dtypes: int64(1), object(10)
memory usage: 13.6+ MB

In [7]:
# Remove unwanted characters and convert to numeric
import pandas as pd

# Clean and convert 'rating'
data['rating'] = pd.to_numeric(data['rating'], errors='coerce').fillna(0)

# Clean and convert 'rating_count'
data['rating_count'] = data['rating_count'].astype(str)

# Remove non-numeric characters (+ and string)

data['rating_count'] = data['rating_count'].str.replace(r'[^0-9]', '', regex=True)

# Convert to numeric
data['rating_count'] = pd.to_numeric(data['rating_count'], errors='coerce').fillna(0).astype(int)

# Convert to string first to avoid errors
data['cost'] = data['cost'].astype(str)

# Remove non-numeric characters (₹ and spaces)
data['cost'] = data['cost'].str.replace(r'[^0-9]', '', regex=True)

# Convert to numeric
data['cost'] = pd.to_numeric(data['cost'], errors='coerce')

# Display data
display(data.head())

,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,567335,AB FOODS POINT,Abohar,0.0,0,200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50,200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100,100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20,250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,0.0,0,250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [8]:
# Datatype check
data.info()

# Save the cleaned data to a new CSV file
data.to_csv("cleaned_data.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 148255 entries, 0 to 148540
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            148255 non-null  int64
 1   name          148255 non-null  object
 2   city          148255 non-null  object
 3   rating        148255 non-null  float64
 4   rating_count  148255 non-null  int64
 5   cost          148255 non-null  int64
 6   cuisine       148255 non-null  object
 7   lic_no        148255 non-null  object
 8   link          148255 non-null  object
 9   address       148255 non-null  object
 10  menu          148255 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 13.6+ MB

In [9]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import pickle

# Load the dataset
df = pd.read_csv('cleaned_data.csv', index_col=0)

# Limit high-cardinality features
def limit_categories(series, top_n):
    top_categories = series.value_counts().nlargest(top_n).index
    return series.where(series.isin(top_categories), other='Other')

df['name'] = limit_categories(df['name'], top_n=500)
df['city'] = limit_categories(df['city'], top_n=100)
df['cuisine'] = limit_categories(df['cuisine'], top_n=200)

# Select columns to encode
categorical_cols = ['name', 'city', 'cuisine']

# Apply One-Hot Encoding
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded = encoder.fit_transform(df[categorical_cols])

# Build DataFrame with encoded features
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_cols), index=df.index)

# Merge with remaining columns
df_numeric = df.drop(columns=categorical_cols)
final_df = pd.concat([df_numeric, encoded_df], axis=1)

# Save encoder
with open('encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

# Save encoded dataset
final_df.to_csv('encoded_data.csv')

In [10]:
# Index matching check
import pandas as pd

# Load both the data files
cleaned_df = pd.read_csv("cleaned_data.csv")
encoded_df = pd.read_csv("encoded_data.csv")

# Check row counts
if cleaned_df.shape[0] == encoded_df.shape[0]:
    print("Number of row counts are matching.")
else:
    print("The row counts are not maching")

# Check index match
if (cleaned_df.index == encoded_df.index).all():
    print("Indices are correctly matching.")
else:
    print("Indices are not matching. Re-set again")
    cleaned_df.reset_index(drop=True, inplace=True)
    encoded_df.reset_index(drop=True, inplace=True)
    print("Indices are resetted and matched correctly.")

Number of row counts are matching.
Indices are correctly matching.

In [11]:
# Install scikit learn package to access sklearn
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

In [12]:
import pandas as pd
import numpy as np
import pickle
from sklearn.cluster import KMeans

# Load encoded data
encoded_data = pd.read_csv("encoded_data.csv")

# Ensure all values are numeric
encoded_data = encoded_data.select_dtypes(include=[np.number])

# Define number of clusters-this cluster value may vary depend on requirement
num_clusters = 5

# Initialize and fit K-Means model
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
encoded_data['Cluster'] = kmeans.fit_predict(encoded_data)

# Save cluster labels
encoded_data.to_csv("clustered_data.csv", index=False)

# Save K-Means model
with open("kmeans_model.pkl", "wb") as f:
    pickle.dump(kmeans, f)

In [7]:
import pandas as pd

# Load original cleaned dataset
original_df = pd.read_csv("cleaned_data.csv")

# Load encoded dataset
encoded_df = pd.read_csv("encoded_data.csv")

In [11]:
# Example: Indices of similar restaurants
recommended_indices = [12, 45, 78]
recommended_restaurants = original_df.iloc[recommended_indices]

# Print recommended restaurant detail
display(recommended_restaurants[['name', 'address', 'cuisine', 'rating']])

,name,address,cuisine,rating
12,Swastik Dhaba,"Swastik Dhaba, Gaushala road street no 22 near...",North Indian,0.0
45,Frankie roll junction,"Frankie roll junction, lajpat rai market near ...","North Indian,Fast Food",0.0
78,Lotus Grand Family Restaurant,"Lotus Grand Family Restaurant, opp bustand Adi...",Biryani,3.6